/***************************************************************************
 *
 * Licensed Materials - Property of IBM
 * 
 * Restricted Materials of IBM 
 * 
 * IBM Informix Dynamic Server
 * (c) Copyright IBM Corporation 2014 All rights reserverd.
 *
 *
 *  Title            : usage.c
 *  Author           : Cosmo@uk.ibm.com
 *  Description      : Usage file for Parallel TimeSeries Loader
 *
 *  Version          : 1.0	2015-02-13 Created by cosmo@uk.ibm.com
 *
 ****************************************************************************
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

#include "mi_search.h"

#include "defs.h"

/*
** This file has all the usage options and prints out a basic man page
** for use with txt2man.
**
** Any changes to options should go here and the TSLoader.txt file
** should also be updated if there are option or feature changes.
*/

/*
  TODO: Get the --new-ts feature working properly.
  
  --new-ts 'timeseries'  To provision a new TimeSeries a specifcation string
  	   		 must be supplied. If it does not have a reference to
			 a container then the least used container will be used.
*/

void version (void)
{
    extern char TSLoader_ver[], esql_ver[], uname_ver[], args_ver[];

    printf ("%s\n%s\n%s\n%s\n", TSLoader_ver, esql_ver, args_ver, uname_ver);

    exit (0);
}

void description (void)
{
/* This include is generated by the Makefile from TSLoader.txt */
#include "description.c"

}

void options (void)
{
    printf ("  TSL_Init [ --verbose ] --database dbname --table tabname --column ts_column\n");
    printf ("           [ --user username --password passwd ]\n");
#ifdef ENABLE_GRID
    printf ("           [ --meta-table metaname ] [ --grid gridname ]\n");
#endif
    printf ("           [ --logfile /path/to/message.log ] [ --datetime dt_format ]\n\n");
    printf ("  TSL_Load [ --verbose ] --database dbname --table tabname --column ts_column\n");
    printf ("           [ --user username --password passwd ]\n");
    printf ("           { --input { file | '-' } | --indput-dir dirname }\n");
    printf ("           [ --readers nreaders ] [ --one-shot ]\n");
#ifdef ENABLE_GRID
    printf ("           [ --meta-table metaname --meta-join column ] [ --grid gridname ]\n");
#endif
    printf ("           [ --tx-size nrows ] [ --status nseconds ] [ --tsl-rejects /path/to/TSL_rejects.log ]\n");
    printf ("           [ --repeat-marker nelements ] [ --lock-containers ] [ --no-info ]\n");
    printf ("           [ --put-count nbuffers ] [ --put-buffer buffsize ] [ --putbuf-dir dirname ]\n");
    printf ("           [ --rejects /path/to/rejects.log ] [ --ifs '|' ] [ --threads N ] \n");
    printf ("           [ --reduced-log ] [ --flush-flag N ] [ --remove-allnulls ]\n");
    printf ("           [ --skip-repeat-columns [ ncols ] ]\n");
    printf ("           [ --to-utc column_number ] [ --pass-through { 0 | 1 | 2 } ] [ --fix-non-ascii ]\n");
    printf ("           [ --flush-interval ]\n\n");
    printf ("  TSL_Shutdown [ --verbose ] --database dbname --table tabname --column ts_column\n");
    printf ("               [ --user username --password passwd ]");
#ifdef ENABLE_GRID
    printf ("\n               [ --meta-table metaname ] [ --grid gridname ]");
#endif
    printf ("\n\n");
}

void usage (char *progname)
{
    printf ("\nUsage:\n\n");

    options ();

    printf ("Try '%s --man' for full details\n\n", progname);

    exit (0);
}

void man (void)
{
    printf ("NAME\n  TSL_Init, TSL_Load, TSL_Shutdown - The Informix TimeSeries TSLoader client\n\nSYNOPSIS\n");

    options ();

    description ();
    
    exit (0);
}
