#!/bin/bash

export INFORMIXDIR=/home/informix/1210FC5
export ONCONFIG=onconfig
export PATH=$INFORMIXDIR/bin:$PATH:.
export INFORMIXSQLHOSTS=$INFORMIXDIR/etc/sqlhosts
export INFORMIXSERVER=informix

export JAVA_HOME=/home/informix/java/jdk1.7.0_60
export PATH=$JAVA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$INFORMIXDIR/lib:$INFORMIXDIR/lib/esql



######################################################################
#
#  Licensed Materials - Property of IBM
#  
#  Restricted Materials of IBM 
#  
#  IBM Informix Dynamic Server
#  (c) Copyright IBM Corporation 2013 All rights reserverd.
# 
# 
#   Title            : TSL_FileLoad
#   Description      : Shell script to load a file
# 
######################################################################

# Simple example of using the 'FILE:' interface to TSL_Put
# Be careful of large files using up memory and log space

db=$1
table=$2
column=$3
file=$4
rej_file=$5
commits=${6:-100620}

[ $# -lt 5 ] && {
    echo "Usage:"
    echo "      $0 database table column input_file reject_file [ commits ]"
}
 

dbaccess ${db} - <<%_EOF_%  2>/dev/null

set isolation to dirty read;
set lock mode to wait;

execute function tsl_attach ('$table','$column','$rej_file');

execute function tsl_put ('$table|$column', 'FILE:$file');

execute function tsl_commit ('$table|$column', 1 ,$commits);

execute function tsl_sessionclose ('$table|$column');

%_EOF_%

exit 0 
